- name: Install and run nginx playbook
  hosts: ansiblehost
  become: yes
  tasks:
    - name: Intsalling nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started




